### ISSUE TITLE
Fix incorrect VRDR IG links in library definitions

### ISSUE THREAD

**Issue by johnarleyburns** [nightingaleproject/VRDR_javalib#15]
[diff-pilottesting-20230405.txt](https://github.com/nightingaleproject/VRDR_javalib/files/11173497/diff-pilottesting-20230405.txt)

Diff from Ms. Tong of UT jurisdiction attached, please apply.

**Comment by MikeRileyGTRI** [comment]
These look ok to me, except in the FhirContext definition, there's an STU2.1 version profile reference vs just a base VRDR profile reference. Is that intentional?

**Comment by johnarleyburns** [comment]
That's a good point, I'm not sure how to handle the IG in this situation,
if we should use an explicit version or not.
