### ISSUE TITLE
VRDR Java Library documentation

### ISSUE THREAD

**Issue by pkmitre** [nightingaleproject/VRDR_javalib#6]
The VRDR Java Library should have documentation in the project README.md file that provides complete instructions for using the library. Instructions should include

* Version information including alignment with VRDR IG
* Initial instructions for building with the library (including examples)
* Instructions for creating records with the library (including examples)
* Instructions for creating messages with the library (including examples)
* Instructions for interacting with the API (including examples)
* Instructions for consuming coded responses from NCHS (including examples)

README should include content similar to the VRDR .NET library at https://github.com/nightingaleproject/vrdr-dotnet/blob/master/README.md

**Comment by johnarleyburns** [comment]
Be sure to also update the contact email to NVSSModernization (CDC) <nvssmodernization@cdc.gov>.
