### ISSUE TITLE
fix:  VRDR Java Library address interpretation

### ISSUE THREAD

**Issue by wswarr** [nightingaleproject/VRDR_javalib#80]
Reported by Maryland:

https://chat.fhir.org/#narrow/stream/179301-Death-on-FHIR/topic/Address.20mismatch

**Comment by whichwit** [comment]
The `_city` and `_district` extensions need to be added to the city and district elements, not to the address. Using the code shared:

```
Extension cityCode = new Extension("http://hl7.org/fhir/us/vrdr/StructureDefinition/CityCode", new PositiveIntType("37000"));
`decedentsHome.getCityElement().addExtension(cityCode);
```
The same goes for other extensions like `_district` or `_state`.
