### ISSUE TITLE
Include OperationOutcome entry during export

### ISSUE THREAD

**Issue by whichwit** [nightingaleproject/VRDR_javalib#85]
When handling ExtractionErrorMessage types, not all entries are included when exporting the object e.g., when `BaseMessage.toJson()` is called. 

The missing entry (OperationOutcome) needs to be explicitly added to the message for this message type.

**Comment by MikeRileyGTRI** [comment]
Are you talking about serialization when you mean "exporting"? Can you provide an example; because the reach of this issue could be large.

**Comment by whichwit** [comment]
Most of the profiles were covered by their definitions. This is more like an edge case where OperationalOutcome were specifically excluded in the profile entry. 

Do you know if there was any historical reason for this behavior?
